# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.TextField(default='http://g-ec2.images-amazon.com/images/G/01/social/api-share/amazon_logo_500500._V323939215_.png'),
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.TextField(default='https://www.amazon.com'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
