# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20160802_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(default='http://g-ec2.images-amazon.com/images/G/01/social/api-share/amazon_logo_500500._V323939215_.png'),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(default='https://www.amazon.com'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
